name: grofast_consumers
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  googleapis_auth: ^1.4.0
  app_settings: ^5.0.0
  intl: ^0.19.0
  get: ^4.6.5
  google_sign_in: ^6.1.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_database: ^11.1.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.3
  image_picker: ^0.8.6
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.2
  animated_splash_screen: ^1.3.0
  page_animation_transition: ^1.0.0
  page_transition: ^2.1.0
  liquid_swipe: ^3.1.0
  iconsax_flutter: ^1.0.0
  get_storage: ^2.1.1
  flutter_custom_clippers: ^2.1.0
  flutter_animate: ^4.4.0
  custom_navigation_bar: ^0.8.2
  responsive_framework: ^1.1.1
  liquid_pull_to_refresh: ^3.0.1
  ionicons: ^0.2.2
  eva_icons_flutter: ^3.1.0
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.9
  enefty_icons: ^1.0.7
  social_media_buttons: ^1.0.0
  pinput: ^4.0.0
  flutter_staggered_animations: ^1.1.1
  coupon_uikit: ^0.2.1
  lorem_ipsum: ^0.0.3
  readmore: ^2.2.0
  vertical_scrollable_tabview: ^0.1.1
  scroll_to_index: ^3.0.1
  fade_shimmer: ^2.2.0
  flutter_speed_dial: ^7.0.0
  toastification: ^1.2.0
  lottie: any
  flutter_rating_bar: ^4.0.1
  percent_indicator: ^4.2.3
  flutter_slidable: ^3.0.1
  swipeable_tile: ^2.0.0+3
  vibration: ^1.8.4
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  connectivity_plus: ^5.0.2
  flutter_native_splash: ^2.4.2
  flutter_localization: ^0.2.2
  flutter_localizations:
    sdk: flutter
  dvhcvn: ^2.0.20240201
  image_network: ^2.5.6
  timelines: ^0.1.0
  easy_stepper: ^0.8.3
  google_maps_flutter: ^2.5.3
  geolocator: ^11.0.0
  geocoding: ^2.2.0
  http: ^1.2.0
  geocode: ^1.0.3
  tuple: ^2.0.2
  firebase_ui_firestore: ^1.7.0
#  flutter_geofire: ^2.0.3
  firebase_messaging: ^15.1.3
  uuid: ^4.3.3
  rounded_background_text: ^0.5.0
  firebase_app_check: ^0.3.1+4
  location: ^5.0.3
  another_stepper: ^1.2.2
  flutter_chat_types: ^3.6.2
  pretty_qr_code: ^3.3.0
  mobile_scanner: ^4.0.1
  cross_file_image: ^1.1.0
  flutter_stripe: ^11.2.0
  flutter_osm_plugin: ^0.70.4
  getx_test: ^1.0.3
  mockito: ^5.4.4
  fake_cloud_firestore: ^3.0.3
  mocktail: ^1.0.3
  firebase_database_mocks: ^0.7.0
  firebase_performance: ^0.10.0+8
  flutter_gemini: ^2.0.3
  flutter_markdown: ^0.6.20
  flutter_local_notifications: ^17.1.2
  flutter_timezone: ^1.0.8
  rxdart: ^0.28.0
  timeago: ^3.6.1
  get_time_ago: ^1.3.1
  diacritic: ^0.1.6
  flutter_fortune_wheel: ^1.3.2
  flutter_chat_ui: ^1.6.15
  file_picker: ^8.1.4
  open_filex: ^4.5.0
  flutter_launcher_icons: ^0.14.1
  cached_network_image: ^3.2.0
  flutter_chat_bubble: ^2.0.2
  dio: ^5.5.0+1
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logos/logogro.jpg"
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/category/
    - assets/images/on_boarding_screen/
    - assets/images/other/
    - assets/logos/


